### ISSUE TITLE
Multi-key fetchs for reduce view error raised when group=true and group_level=1

### ISSUE THREAD

**Issue by wooki** [cloudant/chttpd#20]
Seems to be raised line 170 in https://github.com/cloudant/chttpd/blob/master/src/chttpd_view.erl

I'm posting to my view (with the keys in the http body) with a url encoded set of query parameters and this error is raised even though I include the group = true.

The other parameter is group_level.  Other parameters I have tried substituting for group_level do not cause this error

I need the other group_level though otherwise the sending of the keys is fairly useless.  Is this expected behaviour?  

Nothing I have read seems to say that these two options should be exclusive.  Certainly they work when I query the view using a get and without the keys being posted.

Thanks.

**Comment by rnewson** [comment]
From https://wiki.apache.org/couchdb/HTTP_view_API#Querying_Options

"Note: Multiple keys request to a reduce function only supports group=true and NO group_level (identical to group_level=exact). The resulting error is "Multi-key fetchs for reduce view must include group=true""

I'll note that group and group_level are mutually exclusive, the error you get is because you did group_level=1 (group=true means group_level=exact). the http code will simply use the last group_level you set, you can see this if you change the order of your parameters.

**Comment by wooki** [comment]
Thanks for your help, sorry I missed that in the docs!
